### ISSUE TITLE
Setting to disable notifications when toggling

### ISSUE THREAD

**Issue by orpheuslummis** [IronGeek/vscode-darklight#1]
Thanks for making this plugin.

**Comment by IronGeek** [comment]
@orpheuslummis thank you for the suggestion.

I've added the feature to controls whether to show/ hide notification in the latest release (v0.1.2)
Please update and let me know if you still have any issues...

**Comment by orpheuslummis** [comment]
Great, works well here on [openvscode-server](https://github.com/gitpod-io/openvscode-server). Thanks!
